backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'sitewide'
    label: 'Sitewide'
    description: "Sitewide Details"
    identifier_field: company_name
    format: 'json'
    folder: 'assets/content/sitewide'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Company Name', name: 'company_name', widget: 'string' }
      - { label: 'Company Logo', name: 'company_logo', widget: 'image', required: false }
      - { label: 'Company Address Line 1', name: 'company_address_line_1', widget: 'string', required: false }
      - { label: 'Company Address Line 2', name: 'company_address_line_2', widget: 'string', required: false }
      - { label: 'Company Address Line 3', name: 'company_address_line_3', widget: 'string', required: false }
      - { label: 'Company Phone Number', name: 'company_phone_number', widget: 'string', required: false }
      - { label: 'Company Email Address', name: 'company_email_address', widget: 'string', required: false }
      - label: "Contact Box - Every Page"
        name: "contact_box"
        widget: "object"
        fields:
        - { label: 'Contact Header', name: 'contact_header', widget: 'string', required: false }
        - { label: 'Contact Para', name: 'contact_para', widget: 'text', required: false }
        - { label: 'Contact Button Link', name: 'contact_button_link', widget: 'string', required: false }
        - { label: 'Contact Button Text', name: 'contact_button_text', widget: 'string', required: false }
      - label: "Footer Details"
        name: "footer_details"
        widget: "object"
        fields:
        - { label: 'Footer - Show Site Links', name: 'footer_show_site_links', widget: 'boolean', required: false }
        - { label: 'Footer Company Para', name: 'footer_company_para', widget: 'text', required: false }
        - { label: 'Footer Copyright', name: 'footer_copyright', widget: 'string', required: false }
      - label: "Social Media"
        name: "social_media"
        widget: "object"
        fields:
        - { label: 'Footer - Show Social Media', name: 'footer_show_social', widget: 'boolean', default: false, required: false }
        - { label: 'Facebook Link', name: 'facebook_link', widget: 'string', required: false }
        - { label: 'Instagram Link', name: 'instagram_link', widget: 'string', required: false }
        - { label: 'Twitter Link', name: 'twitter_link', widget: 'string', required: false }
        - { label: 'GitHub Link', name: 'github_link', widget: 'string', required: false }
        - { label: 'Dribble Link', name: 'dribble_link', widget: 'string', required: false }
      - label: "Contact Form"
        name: "contact_form"
        widget: "object"
        fields:
        - name: 'items'
          label: 'Contact Form Item'
          widget: "list"
          fields:
          - {label: "Text", name: "text", widget: "string"}
          - {label: "Required Item", name: "required", widget: "boolean", default: false, required: false }
          - {label: "Short Name", name: "short_name", widget: "string"}
          - {label: "Placeholder", name: "placeholder", widget: "string", required: false}
          - label: "Field Type"
            name: "type"
            widget: "select"
            options: ["text", "email", "tel", "url"]
        - {label: "Submit Button Text", name: "button_text", widget: "string"}

  - name: 'nav'
    label: 'Nav Items'
    identifier_field: title
    format: 'json'
    folder: 'assets/content/nav'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "All Nav Shown", name: "status", widget: "boolean", default: true, required: false }
      - label: "Nav Items"
        name: "nav_items"
        widget: "list"
        fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: "Shown", name: "status", widget: "boolean", default: true, required: false }
        - { label: 'Short Description', name: 'para', widget: 'text', required: false }
        - { label: 'Link', name: 'link', widget: 'string', required: false }
        - { label: 'Icon', name: 'icon', widget: 'image', required: false }

  - name: 'page'
    label: 'Pages'
    identifier_field: page_name
    format: 'json'
    folder: 'assets/content/page'
    create: true
    slug: '{{page_name}}'
    editor:
      preview: false
    fields:
      - { label: 'Page Name', name: 'page_name', widget: 'string' }
      - label: "Hero"
        name: "hero"
        widget: "object"
        fields:
        - { label: 'Header - Line 1', name: 'hero_header', widget: 'string', required: false }
        - { label: 'Header - Line 2', name: 'hero_header_2', widget: 'string', required: false }
        - { label: 'Para', name: 'hero_para', widget: 'text', required: false }
        - { label: 'Button Text', name: 'hero_button_text', widget: 'string', required: false }
        - { label: 'Button Link', name: 'hero_button_link', widget: 'string', required: false }
        - { label: 'Background Image', name: 'hero_background_image', widget: 'image', required: false }
        - { label: 'Background Video', name: 'hero_background_video', widget: 'file', required: false }
        - { label: 'Sub Image', name: 'hero_sub_image', widget: 'image', required: false }
        - { label: 'Smaller?', name: 'hero_small', widget: 'boolean', default: true, required: false }
      - label: "Page Intro"
        name: "page_intro"
        widget: "object"
        fields:
        - { label: 'Show Intro', name: 'status', widget: 'boolean', default: true, required: false }
        - { label: 'Page Intro Header', name: 'page_intro_header', widget: 'string', required: false }
        - { label: 'Page Intro Header - Line 2', name: 'page_intro_header_2', widget: 'string', required: false }
        - { label: 'Page Intro Header - Line 3', name: 'page_intro_header_3', widget: 'string', required: false }
        - { label: 'Page Intro Para', name: 'page_intro_para', widget: 'text', required: false }
      - label: "Page Sections"
        name: "sections"
        widget: "list"
        slug: '{{header}}'
        fields:
        - { label: 'Header', name: 'header', widget: 'string', required: false }
        - { label: 'Show Section', name: 'status', widget: 'boolean', required: false }
        - label: "Section Text"
          name: "section_text"
          widget: "list"
          fields:
          - { label: 'Text', name: 'text', widget: 'markdown', required: false, buttons: ["bold", "italic", "link", "heading-two", "heading-three", "bulleted-list", "numbered-list"] }

  - name: 'employees'
    label: 'Employees'
    identifier_field: name
    format: 'json'
    folder: 'assets/content/employees'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Employee List Name', name: 'name', widget: 'string', required: false }
      - label: "Employees"
        name: "list"
        widget: "list"
        fields:
        - { label: 'Name', name: 'name', widget: 'string', required: false }
        - { label: 'Show Employee', name: 'status', widget: 'boolean', default: false}
        - { label: 'Title', name: 'title', widget: 'string', required: false }
        - { label: 'Speciality', name: 'speciality', widget: 'string', required: false }
        - { label: 'Email Address', name: 'email', widget: 'string', required: false }
        - { label: 'Headshot', name: 'headshot', widget: 'image', required: false }
        - { label: 'Short Description', name: 'short_text', widget: 'text', required: false }
        - { label: 'Long Text', name: 'long_text', widget: 'markdown', required: false, buttons: ["bold", "italic", "link", "heading-two", "heading-three", "bulleted-list", "numbered-list"] }

  - name: 'platforms'
    label: 'Platforms'
    identifier_field: name
    format: 'json'
    folder: 'assets/content/platforms'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Platform List Name', name: 'name', widget: 'string', required: false }
      - label: "Platforms"
        name: "list"
        widget: "list"
        fields:
        - { label: 'Name', name: 'name', widget: 'string', required: false }
        - { label: 'Show Platform', name: 'status', widget: 'boolean', default: false}
        - { label: 'Logo', name: 'logo', widget: 'image', required: false }
        - { label: 'Website', name: 'website', widget: 'string', required: false }
        - { label: 'Description', name: 'title', widget: 'text', required: false }
        
        